runtime: nodejs16
env_variables:
  PORT: 4000
  DB_URI: mongodb+srv://admin:admin@safespace.n1jfcnc.mongodb.net/?retryWrites=true&w=majority
  JWT_SECRET: JBRON098SROINRIOUHOHSDOKFN948HIFRCN
  JWT_EXPIRE: 500d
  PASSPORT_SECRET: kurnfsnskjdkjsneoufwojncaksjnjns
  COOKIE_EXPIRE: 5
  SMTP_SERVICE: gmail
  SMTP_USER: agrimchopra90@gmail.com
  SMTP_PASS: vmCwdj9U7IFNgcq1
